// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string               `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	TokenExpiration      *timestamp.Timestamp `protobuf:"bytes,2,opt,name=TokenExpiration,proto3" json:"TokenExpiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetTokenExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.TokenExpiration
	}
	return nil
}

type IsEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRequest) Reset()         { *m = IsEmailRequest{} }
func (m *IsEmailRequest) String() string { return proto.CompactTextString(m) }
func (*IsEmailRequest) ProtoMessage()    {}
func (*IsEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *IsEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRequest.Unmarshal(m, b)
}
func (m *IsEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRequest.Marshal(b, m, deterministic)
}
func (m *IsEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRequest.Merge(m, src)
}
func (m *IsEmailRequest) XXX_Size() int {
	return xxx_messageInfo_IsEmailRequest.Size(m)
}
func (m *IsEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRequest proto.InternalMessageInfo

func (m *IsEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IsEmailResponse struct {
	IsEmailRegistered    bool     `protobuf:"varint,1,opt,name=IsEmailRegistered,proto3" json:"IsEmailRegistered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailResponse) Reset()         { *m = IsEmailResponse{} }
func (m *IsEmailResponse) String() string { return proto.CompactTextString(m) }
func (*IsEmailResponse) ProtoMessage()    {}
func (*IsEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *IsEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailResponse.Unmarshal(m, b)
}
func (m *IsEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailResponse.Marshal(b, m, deterministic)
}
func (m *IsEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailResponse.Merge(m, src)
}
func (m *IsEmailResponse) XXX_Size() int {
	return xxx_messageInfo_IsEmailResponse.Size(m)
}
func (m *IsEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailResponse proto.InternalMessageInfo

func (m *IsEmailResponse) GetIsEmailRegistered() bool {
	if m != nil {
		return m.IsEmailRegistered
	}
	return false
}

func init() {
	proto.RegisterType((*SignInRequest)(nil), "auth.SignInRequest")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*IsEmailRequest)(nil), "auth.IsEmailRequest")
	proto.RegisterType((*IsEmailResponse)(nil), "auth.IsEmailResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x6d, 0x45, 0x4b, 0x9d, 0x45, 0x8b, 0xb1, 0x42, 0xc9, 0x45, 0xc9, 0x41, 0x3c, 0x48, 0x0a,
	0xf5, 0x03, 0x44, 0xb1, 0x48, 0x6f, 0xb2, 0xad, 0x1f, 0x90, 0xb6, 0xe3, 0x1a, 0xec, 0x26, 0x6b,
	0x92, 0x55, 0x6f, 0xfe, 0xba, 0xbb, 0xc9, 0x66, 0xa1, 0xb5, 0xb7, 0x79, 0xef, 0xcd, 0x9b, 0x79,
	0x3c, 0x00, 0x51, 0xba, 0x77, 0x5e, 0x18, 0xed, 0x34, 0x39, 0xac, 0x67, 0x7a, 0x99, 0x69, 0x9d,
	0x6d, 0x70, 0xec, 0xb9, 0x65, 0xf9, 0x36, 0x76, 0x32, 0x47, 0xeb, 0x44, 0x5e, 0x84, 0x35, 0xf6,
	0x0c, 0x27, 0x73, 0x99, 0xa9, 0x99, 0x4a, 0xf1, 0xb3, 0xac, 0x14, 0x42, 0xa1, 0xff, 0x6a, 0xd1,
	0x28, 0x91, 0xe3, 0xa8, 0x7b, 0xd5, 0xbd, 0x39, 0x4e, 0x5b, 0x5c, 0x6b, 0x2f, 0xc2, 0xda, 0x6f,
	0x6d, 0xd6, 0xa3, 0x83, 0xa0, 0x45, 0xcc, 0x56, 0x70, 0xb4, 0xd0, 0x1f, 0xa8, 0xc8, 0xb0, 0x19,
	0x1a, 0x77, 0xc3, 0x3e, 0xc1, 0xc0, 0x0f, 0xd3, 0x9f, 0x42, 0x1a, 0xe1, 0xa4, 0x56, 0xfe, 0x42,
	0x32, 0xa1, 0x3c, 0x44, 0xe4, 0x31, 0x22, 0x5f, 0xc4, 0x88, 0xe9, 0xae, 0x85, 0x5d, 0xc3, 0xe9,
	0xcc, 0x4e, 0x73, 0x21, 0x37, 0x31, 0x6e, 0xf5, 0xcd, 0xe3, 0xf8, 0xcd, 0x03, 0x76, 0x0f, 0x83,
	0x76, 0xcf, 0x16, 0x5a, 0x59, 0x24, 0xb7, 0x70, 0xd6, 0x52, 0x99, 0xb4, 0x0e, 0x0d, 0xae, 0xbd,
	0xa9, 0x9f, 0xfe, 0x17, 0x26, 0xbf, 0x90, 0x3c, 0x54, 0xfd, 0xcd, 0xd1, 0x7c, 0xc9, 0x55, 0x6d,
	0xee, 0x85, 0x96, 0xc8, 0x39, 0xf7, 0x1d, 0x6f, 0x75, 0x46, 0x93, 0x40, 0xfa, 0xb4, 0xac, 0x43,
	0x1e, 0xf7, 0xbc, 0x22, 0xc3, 0xb0, 0xb3, 0x1d, 0x9f, 0x5e, 0xec, 0xb0, 0x21, 0x2c, 0xeb, 0x2c,
	0x7b, 0xbe, 0x8e, 0xbb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x5d, 0x88, 0x79, 0xd3, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*Token, error)
	IsEmailRegistered(ctx context.Context, in *IsEmailRequest, opts ...grpc.CallOption) (*IsEmailResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/auth.AuthService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) IsEmailRegistered(ctx context.Context, in *IsEmailRequest, opts ...grpc.CallOption) (*IsEmailResponse, error) {
	out := new(IsEmailResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthService/IsEmailRegistered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	SignIn(context.Context, *SignInRequest) (*Token, error)
	IsEmailRegistered(context.Context, *IsEmailRequest) (*IsEmailResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthServiceServer) IsEmailRegistered(ctx context.Context, req *IsEmailRequest) (*IsEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsEmailRegistered not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_IsEmailRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IsEmailRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/IsEmailRegistered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IsEmailRegistered(ctx, req.(*IsEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _AuthService_SignIn_Handler,
		},
		{
			MethodName: "IsEmailRegistered",
			Handler:    _AuthService_IsEmailRegistered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
